version: "3.3"

services:
  mongodb:
    image: mongo:5.0.17
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_DATABASE: database
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet || exit 1
      interval: 5s
      retries: 3
      start_period: 20s

  vieback:
    image: 7upnamk/vie-back:latest
    build:
      context: ./backend
    container_name: vieback
    restart: unless-stopped
    environment:
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_DATABASE=database
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend
    depends_on:
      mongodb:
        condition: service_healthy
  viefront:
    image: 7upnamk/vie-front:latest
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: "http://localhost:5000"
        REACT_APP_USERS_ENDPOINT: "/students"
    container_name: viefront
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - vieback

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  database:
